@extends('new_collection.layouts.app')
    
@section('content')
        <div class="main-part">
            <section class="banner-part" style="background: url('{{ asset('_new_collection/assets/images/banner1.png') }}') no-repeat center center; background-size:cover;">
                <div class="container">
                    <div class="banner-inner">
                        <h2>Terms and Conditions</h2>
                    </div>
                </div>
            </section>
            <section class="about-part">
                <div class="container">
                    <div class="about-inner">
                        <p><strong>Date of Last Revision: [DATE]</strong></p>
                        <p>Welcome to the Clarkin Collection website (the “Website”). These  Terms of Use (the “Agreement”) constitute a legally binding agreement  made by and between CLARKIN COLLECTION, LLC, a California limited  liability company dba Clarkin Creation (“we”, “us”, “our”, or “Clarkin”)  and the users and/or purchasers of all of our Websites, applications,  content, photographs, art, text, graphics, logos, images, products and  services (the “Services”), whether personally or on behalf of an entity  (“you” or “your”). This Agreement governs your use of the Services  offered by Clarkin, so please read it carefully. </p>
                        <p>PLEASE NOTE THAT BY ACCESSING OR USING ANY PART OF THE SERVICES,  REGARDLESS OF HOW YOU INTERACT WITH US – ONLINE, MOBILE, THROUGH A  STORE, OR IN ANY OTHER MANNER, YOU AGREE THAT YOU HAVE READ, UNDERSTAND  AND AGREE TO BE BOUND BY THIS AGREEMENT. IF YOU DO NOT AGREE TO BE SO  BOUND, DO NOT ACCESS OR USE THE SERVICES. CLARKIN RESERVES THE RIGHT TO  MAKE CHANGES TO THIS AGREEMENT AT ANY TIME. YOUR CONTINUED USE OF THE  SERVICES CONSTITUTES ASSENT TO ANY NEW PROVISIONS OF THIS AGREEMENT THAT  MAY BE POSTED WITHIN THE SERVICES IN THE FUTURE.</p>
                        <p>You acknowledge that the Services may be provided under various  Clarkin websites, vendors, or stores, which may be provided by Clarkin  subsidiaries and affiliates and/or independent third-party businesses.</p>
                        <p>Only persons of legal age can accept this Agreement. You hereby  represent that you are at least 18 years old, or the age of legal  majority in your jurisdiction and that you are legally able to enter  into this Agreement.</p>
                        <p>The Services are protected by copyright under both United States  and foreign laws and are exclusively owned by Clarkin. Any use of the  Services not expressly permitted by the Agreement is a breach of the  Agreement and may violate copyright, trademark, and other laws.  Materials from the Services are subject to change or removal without  notice in the sole discretion of Clarkin. All rights not expressly  granted herein are reserved to Clarkin.</p>
                        <p>Provided that you are eligible to use the Services, you are  granted a limited, non-exclusive, non-sublicensable, revocable,  non-transferrable license to access and use the Services in connection  with your use of the Services for personal, noncommercial use, provided  that you do not obscure, alter or delete any trademark, copyright, or  other proprietary notices.</p>
                        <p>You may not alter or remove any copyright and/or proprietary  rights notices that are contained in materials from the Services. You  may not upload or republish the Services’ content on any Internet,  Intranet or Extranet site or use the information in any other database  or compilation, and any other use of the Services’ content is strictly  prohibited. Your license is subject to this Agreement and does not  permit use of any data mining, robots, scraping or similar data  gathering or extraction methods. Any use of the Services beyond the  scope of the license granted above is prohibited. The limited license  granted by Clarkin terminates if you do not comply with all conditions  of use set forth in this Agreement. Your permission to use the Services  automatically terminates and you must immediately destroy any copies  that you have made of materials from the Services.</p>
                        <p>All materials in the Services, including without limitation, the  Clarkin logo, designs, text, graphics, information, data, images, audio,  video, applications, software, metadata, compilations, graphical user  interfaces, other files, and the selection, arrangement and organization  thereof are either owned by Clarkin or are the property of Clarkin’s  suppliers or licensors. No Services content may be modified, copied,  distributed, framed, reproduced, republished, downloaded, scraped,  displayed, posted, transmitted, or sold in any form or by any means, in  whole or in part, without our prior written permission.</p>
                        <p>Clarkin, the Clarkin logo, and the other Clarkin product names,  tag lines, page headers, custom graphics, button icons, and scripts  shown on the Services are service marks, trademarks or trade dress of  Clarkin. Any use by you of such marks or trade dress is for the sole  benefit of Clarkin and all goodwill generated by such use will inure  solely to Clarkin. If you refer to Clarkin’s marks or logos, you must  include appropriate attribution to Clarkin. All other service marks,  trademarks, trade names and the like that appear on the Services are the  property of their respective owners. You may not use (including as  part of a domain name) any of these marks, trade dress, or trade names  without express permission, including, without limitation, in connection  with any product or service that is not Clarkin’s or in any manner that  is likely to cause confusion among customers, or in any manner that  disparages or discredits Clarkin.</p>
                        <p>Clarkin retains ownership of its intellectual property rights and  you do not obtain any rights therein by virtue of this Agreement or  otherwise. You have no right to use, copy, display, perform, publish,  create derivative works from, create new works or abstracts from,  distribute, have distributed, or sublicense materials or content  available on the Services, except as set forth in this Agreement.</p>
                        <p>Each party represents and warrants to the other party: (1) that it  has the full power and authority to enter into and perform its  obligations under this Agreement; (2) the assent to and performance by  it of its obligations under this Agreement do not constitute a breach of  or conflict with any other agreement or arrangement by which it is  bound, or any applicable laws, regulations or rules; and (3) this  Agreement constitutes legal, valid and binding obligations of the  parties executing or assenting to this Agreement, enforceable in  accordance with its terms and conditions, except that: (i) such  enforceability may be limited by bankruptcy, insolvency, reorganization,  moratorium, fraudulent transfer or other laws, now or hereafter in  effect, affecting creditors’ rights and remedies generally, and (ii) the  remedies of specific performance and injunctive and other forms of  equitable relief may be subject to equitable defense and to the  discretion of the court before which any proceeding therefor may be  brought.</p>
                        <p>You represent and warrant to Clarkin that: (1) you will not  infringe the patent, copyright, trademark, trade secret, right of  publicity or other intellectual or proprietary right of any third party  in your use of the Services; and (2) you will comply with all applicable  laws, rules and regulations in your use of the Services, including this  Agreement.</p>
                        <p>By accepting this Agreement, you have represented that you are at  least 18 years old, or the age of legal majority in your jurisdiction,  and that you are legally able to enter into this Agreement. That is why  you are allowed to use the Services. You are strictly prohibited from  assigning your right to use the Services to any person or entity and are  prohibited from assigning your right to use the Services to any persons  under the age of 18, unless they are accompanied by you. If a Clarkin  service provider asks to see proof of identity you agree that you may be  denied use of the Services if you refuse to comply or the proof of  identity does not match the information provided with respect to the  Account being used. You further agree to comply with all applicable  state and federal laws when using the Services and you acknowledge you  may only use the Services for lawful purposes. You are strictly  prohibited from using the Services in a manner that creates a nuisance,  annoyance, inconvenience or property damage.</p>
                        <p>Your use of the Services requires an internet connection, which  may incur data and messaging rates and fees. You are solely responsible  for payment of those rates and fees. You are also responsible for  acquiring a device that is compatible with the Services, and Clarkin  does not represent or warrant in any way that the Services, or any  portion thereof, will be compatible with your device. You also  acknowledge that Clarkin has no control over the internet speed and  quality you are receiving on your device. You shall not hold Clarkin  liable for any damages arising out of, relating to or connected with  delays and/or malfunctions of your device and the internet connection  you are receiving.</p>
                        <p>Clarkin provides the Services for a fee. You acknowledge that  after you have received the Services Clarkin will charge you a final,  non-refundable fee, inclusive of applicable taxes where required by law.  All charges are due immediately and will be charged to the preferred  payment method designated in your Account. You may cancel your request  for Services at any time prior to production of the Services; Clarkin  reserves the right to charge you a cancellation fee. Clarkin further  reserves the right to alter charges for any or all Services at any time  in Clarkin’s sole discretion. You will receive a receipt by email after  your preferred payment method has been charged. In the event your  preferred payment method has been declined, you authorize Clarkin to  charge all applicable fees to a secondary payment method associated with  your Account, if available.</p>
                        <p>In its sole discretion, Clarkin may create promotional codes you  may use to redeem for Account credit, or as may be designated by  Clarkin, other applicable credits related to your use of the Services.  You shall not duplicate, sell or transfer promotional codes in any  manner or make them available to the general public, unless expressly  authorized by Clarkin. You acknowledge that Clarkin may disable  promotional codes at any time and for any reason without liability to  Clarkin. You further acknowledge that promotional codes may not be  redeemed for cash and may expire prior to your use. If Clarkin  believes you have received a credit related to your use of the Services  in error and/or it was obtained fraudulently, illegally, or in violation  of the applicable promotional code’s terms or this Agreement, Clarkin  may withhold or deduct those credits from your Account without prior  notice.</p>
                        <p>You agree to defend, indemnify and hold Clarkin and its employees,  representatives, agents, attorneys, affiliates, directors, officers,  managers and shareholders (the “Indemnified Parties”) harmless from any  damage, loss, cost or expense including without limitation, attorneys’  fees and costs, and expert fees incurred in connection with any  third-party claim, demand or action (“Claim”) brought or asserted  against any of the indemnified Parties: (1) alleging facts or  circumstances that would constitute a breach of any provision of this  Agreement by you or; (2) arising from, related to or connected with your  use of the Services. If you are obligated to provide indemnification  pursuant to this provision, Clarkin may, in its sole discretion, control  the defense, settlement and disposition of any Claim at your sole cost  and expense. Without limiting the foregoing, you may not settle,  compromise or in any other manner dispose of any Claim without the  consent of Clarkin.</p>
                        <p>CLARKIN PROVIDES THE SERVICES ON AN “AS IS” AND “AS AVAILABLE”  BASIS. CLARKIN DOES NOT REPRESENT OR WARRANT THAT THE SERVICES OR THEIR  USE (REGARDLESS OF HOW YOU INTERACT WITH US – ONLINE, MOBILE, THROUGH A  STORE, OR IN ANY OTHER MANNER): (1) WILL BE FREE OF DEFECTS,  INACCURACIES OR ERRORS; (2) WILL MEET YOUR REQUIREMENTS; OR (3) WILL  OPERATE IN THE CONFIGURATION OR WITH OTHER HARDWARE, DEVICE OR SOFTWARE  YOU USE. YOU AGREE THAT THE ENTIRE RISK ARISING OUT OF, RELATED TO OR  CONNECTED WITH YOUR USE OF THE SERVICES REMAINS SOLELY WITH YOU.  CLARKIN MAKES NO WARRANTIES OTHER THAN THOSE EXPRESSLY MADE IN THIS  AGREEMENT, AND HEREBY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES,  INCLUDING WITHOUT LIMITATION, WARRANTIES OF FITNESS FOR A PARTICULAR  PURPOSE, MERCHANTABILITY AND NONINFRINGEMENT.</p>
                        <p>THE THIRD-PARTY LINKS, SERVICES, GOODS, RESOURCES AND INFORMATION  THAT CLARKIN PROVIDES ON OR MAKES AVAILABLE THROUGH THE SERVICES,  INCLUDING, WITHOUT LIMITATION, THOSE AVAILABLE THROUGH THIRD-PARTY  ADVERTISEMENTS, ARE NOT CONTROLLED BY CLARKIN. ACCORDINGLY, CLARKIN  MAKES NO WARRANTIES REGARDING SUCH THIRD-PARTY SERVICES, RESOURCES, AND  INFORMATION, INCLUDING WITHOUT LIMITATION, WARRANTIES OF FITNESS FOR A  PARTICULAR PURPOSE, MERCHANTABILITY, AND NON-INFRINGEMENT, AND WILL NOT  BE LIABLE FOR YOUR USE OF OR RELIANCE ON SUCH THIRD PARTY SERVICES,  RESOURCES OR INFORMATION.</p>
                        <p>YOU ACKNOWLEDGE THAT DIFFERENT TERMS OF USE AND PRIVACY POLICIES  MAY APPLY TO YOUR USE OF THIRD PARTY SERVICES AND CONTENT THAT CLARKIN  DOES NOT CONTROL. CLARKIN SHALL NOT BE RESPONSIBLE OR LIABLE FOR ANY  PRODUCTS OR SERVICES OF SUCH THIRD PARTY PROVIDERS (E.G., APPLE INC.,  GOOGLE, INC., MICROSOFT CORPORATION AND BLACKBERRY LIMITED).</p>
                        <p>Clarkin respects the intellectual property rights of others and  expects its users to do the same. Clarkin may remove content that, in  its sole discretion, appears to infringe the intellectual property  rights of others.</p>
                        <p>Except as otherwise indicated, all content within the Services,  including text, graphics, logos, button icons, photos, images, forms,  audio, video, questionnaires, and software, is the property of Clarkin  or its licensors and is protected by the United States and international  copyright laws. The Digital Millennium Copyright Act of 1998 (the  “DMCA”) provides recourse for copyright owners who believe that material  appearing on the Internet infringes their rights under U.S. copyright  law. If you believe in good faith that materials appearing within the  Services infringe your copyright, you (or your agent) may send us a  notice requesting that the material be removed, or access to it blocked.  In addition, if you believe in good faith that a notice of copyright  infringement has been wrongfully filed against you, the DMCA permits you  to send us a counter-notice. Notices and counter-notices must meet  statutory requirements imposed by the DMCA. One place to find more  information is the U.S. Copyright Office website, currently located at  http:www.loc.gov/copyright.</p>
                        <p>In accordance with the DMCA, Clarkin has designated an agent to  receive notification of alleged copyright infringement. Any written  Notification of Claimed Infringement should comply with Title 17, United  States Code, Section 512(c)(3)(A) and should be provided in writing to  our designated agent as follows:</p>
                        <p><strong>Agent:</strong>? <br> <strong>Address:</strong> 4425 BAYARD ST STE 140, SAN DIEGO CA 92109. <br>?<strong>Phone:</strong> <br> ?<strong>Email:</strong></p>
                        <p><strong>(This telephone number is for copyright-related complaints only. No solicitations.)</strong></p>
                        <p><strong>Please note:</strong> If you materially misrepresent that online material,  product, or activity is infringing your copyrights, you may be liable  for damages (including court costs, attorneys’ fees and expert fees) and  could be subject to criminal prosecution for perjury. We suggest that  you consult your legal advisor before filing a notice or counter-notice.</p>
                        <p>CLARKIN SHALL NOT BE LIABLE TO YOU OR TO ANY THIRD PARTY FOR ANY  CONSEQUENTIAL, INCIDENTAL, INDIRECT, PUNITIVE OR SPECIAL DAMAGES  (INCLUDING DAMAGES RELATING TO LOST PROFITS, LOST DATA, LOSS OF GOODWILL  OR PROPERTY DAMAGE) ARISING OUT OF, RELATING TO OR CONNECTED WITH THE  USE OF THE SERVICES, BASED ON ANY CAUSE OF ACTION, WHETHER IN WARRANTY,  CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, EVEN IF ADVISED OF THE  POSSIBILITY OF SUCH DAMAGES.</p>
                        <p>IF CLARKIN SHALL BE FOUND LIABLE FOR ANY DAMAGES, YOU AGREE THAT  SUCH DAMAGES SHALL ONLY INCLUDE ACTUAL DAMAGES INCURRED BY YOU, AND IN  NO EVENT, WILL CLARKIN’S LIABILITY ARISING OUT OF, RELATING TO OR  CONNECTED WITH THIS AGREEMENT EXCEED ANY PRODUCT OR ERVICE REPLACEMENT  COST. THE LIMITATIONS AND DISCLAIMER IN THIS SECTION ARE NOT INTENDED TO  ALTER YOUR RIGHTS AS A CONSUMER THAT CANNOT BE EXCLUDED UNDER  APPLICABLE LAW. </p>
                        <p>BY ENTERING INTO THIS AGREEMENT, YOU KNOWINGLY AND VOLUNTARILY  AGREE TO BRING ANY CLAIMS GOVERNED BY THIS AGREEMENT IN YOUR INDIVIDUAL  CAPACITY AND NOT AS A PLAINTIFF, CLASS MEMBER, OR REPRESENTATIVE IN ANY  PURPORTED CLASS OR REPRESENTATIVE ACTION. YOU THEREFORE AGREE TO WAIVE  ANY RIGHT TO PARTICIPATE IN ANY REPRESENTATIVE OR CLASS ACTION  PROCEEDING RELATED TO ANY CLAIMS ARISING OUT OF, RELATED TO OR CONNECTED  WITH THIS AGREEMENT. </p>
                        <p>Clarkin will not be liable for failing to perform under this  Agreement by the occurrence of any event beyond its reasonable control,  including, without limitation, a labor disturbance, an Internet outage  or interruption of service, a communications outage, failure by a  service provider to CLARKIN to perform, fire, terrorism, natural  disaster or war.</p>
                        <p>Clarkin may, in its sole discretion, change, modify, suspend, make  improvements to or discontinue any aspect of the SERVICES, temporarily  or permanently, at any time without notice to you, and Clarkin will not  be liable for doing so.</p>
                        <p>All notices required or permitted to be given under  this Agreement will be in writing and delivered to the other party by  any of the following methods: (i) hand delivery, (ii) certified U.S.  mail, return receipt requested, postage prepaid, (iii) overnight  courier, or (iv) electronic mail. If you give notice to us you must use  the following address: CLARKIN COLLECTION, LLC, 4425 BAYARD ST STE 140, SAN DIEGO CA 92109.  If Clarkin provides notice to you, we will use the contact information  provided by you to us. All notices will be deemed received as follows:  (i) if by hand-delivery, on the date of delivery, (ii) if by delivery  by U.S. mail, on the date of receipt appearing on a return receipt card,  (iii) if by overnight courier, on the date receipt is confirmed by such  courier service, or (iv) if by electronic mail, 24 hours after the  message was sent, if no "system error" or other notice of non-delivery  is generated. When you use our Services or send e-mails to us, you are  communicating with us electronically. You consent to receive  communications from us electronically. We will communicate with you by  e-mail or by posting notices on the Website. Each party agrees that any  notice that it receives from the other party electronically satisfies  any legal requirement that such communications be in writing.</p>
                        <p>You acknowledge and agree that, regardless of any statute or law  to the contrary, any claim or cause of action you may have arising out  of, relating to or connected with your use of the Services, must: (1) be  filed within one (1) calendar year after such claim or cause of action  arises, or forever be barred; (2) be decided exclusively under the laws  of California, without regard to the principles of conflicts of law; (3)  be brought and decided exclusively in the state or federal courts in  San Diego County, California; and (4) both parties waive any right  either of us may have to assert the doctrine of forum non conveniens  or similar doctrine or to object to the venue with respect to any  proceeding brought in accordance with this Section. In the event of any  controversy, claim, or dispute between you and Clarkin, arising out of,  relating to or connected with this Agreement occurs, the prevailing  party shall be entitled to recover from the other party reasonable  expenses, attorneys’ fees and costs, including expert and consultant  fees.</p>
                        <p>This Agreement contains the entire understanding between you and  Clarkin regarding its subject matter, and supersedes all prior and  contemporaneous agreements and understandings between us, whether oral  or in writing, regarding its subject matter.</p>
                        <p>This Agreement is binding upon each party hereto and its  successors and permitted assigns. This Agreement and all of your rights  and obligations under it is not assignable or transferable by you  without the prior written consent of Clarkin. This Agreement governs  the relationship between Clarkin and you and does not create any  third-party beneficiary rights. No failure or delay by a party in  exercising any right, power or privilege under this Agreement will  operate as a waiver thereof, nor will any single or partial exercise of  any right, power or privilege preclude any other or further exercise  thereof, or the exercise of any other right, power, or privilege under  this Agreement. The invalidity or unenforceability of any provision of  this Agreement will not invalidate any other provision of this  Agreement, all of which will remain in full force and effect. If you  reside in or are subject to the laws of a jurisdiction anywhere in the  world whose common, statutory, regulatory, or codified law would void  this Agreement in whole or in any essential part (the essential parts  being at least, but not only, the choice of law and exclusive venue  provisions, disclaimers, exclusions and limitations), or which make  accessing the Services illegal, you do so entirely at your own risk.</p>
                        <p><strong>Copyright © 2017, CLARKIN COLLECTION, LLC. All rights reserved.</strong></p>
                    </div>
                </div>
            </section>
        </div>
@endsection